name: Deploy

on:
  push:
    branches:
      - development
      - base

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name }}

    env:
      LAMBDA_NAME: digitized_image_trigger
      LAMBDA_HANDLER_CODE: src/handle_digitized_image_trigger.py
      BASENAME: handle_digitized_image_trigger.py

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Export secrets to environment variables
        uses: oNaiPs/secrets-to-env-action@v1.8
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Make zip file
        run: |
          cp ${{ env.LAMBDA_HANDLER_CODE }} ${{ env.BASENAME }}
          zip ${{ env.LAMBDA_NAME }}.zip ${{ env.BASENAME }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          role-skip-session-tagging: true
          role-duration-seconds: 900

      - name: Upload file to S3
        run: aws s3 cp $LAMBDA_NAME.zip s3://${{ secrets.LAMBDA_BUCKET_NAME }}/$LAMBDA_NAME.zip

      - name: Deploy lambda package
        run: aws lambda update-function-code
          --function-name arn:aws:lambda:${{ secrets.AWS_REGION }}:${{ secrets.AWS_LAMBDA_ACCOUNT_ID }}:function:$LAMBDA_NAME
          --zip-file fileb://$LAMBDA_NAME.zip
